[package]
name = "mlua-module-macos-repro"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { version = "0.11.2", features = ["module", "lua51"] }
